### PR TITLE
build flavours introduced: playstore and fdroid

### PR DESCRIPTION
**Pull request by danielegobbetti**
Added manifest file for fdroid flavour, removing the google play services inclusion.

The fdroid flavour gives a compile error because of the missing inclusion, an alternative
like https://github.com/mar-v-in/NoAnalytics must be intrduced.

This fixes https://github.com/SASAbus/SASAbus/issues/14

### CODE REVIEW

**Comment by danielegobbetti** [comment]
bump?

**Comment by markuswindegger** [comment]
Sorry, I'm not so handy with the github notifications, sometimes I forget them to read...;-)

**Comment by danielegobbetti** [comment]
no problem :)

may I go on with the next pull request or do you prefer to handle it differently?

**Comment by markuswindegger** [comment]
Make a pull request. I will merge it tomorrow then. I changed my primary email, so I think that I will be able to move on much faster with all the requests and issues...

Am 01.12.2015 10:09 nachm. schrieb Daniele Gobbetti <notifications@github.com>:

no problem :)

may I go on with the next pull request or do you prefer to handle it differently?

-
Reply to this email directly or view it on GitHub<https://github.com/SASAbus/SASAbus/pull/15#issuecomment-161096409>.

________________________________

Markus Windegger
IT Manager
SASA SpA-AG

Tel +39 0471 519 603
Fax +39 0471 519 599
Mobil +39 366 90 35 886
eMail windegger@sasabz.it

[http://open.sasabz.it/files/logo/sasalogo_small.gif]

Sede / Sitz
SASA SpA-AG
via Buozzi 8 / Buozzistrasse 8
39100 Bolzano / Bozen
Cap. Sociale / Gesellschaftskapital EUR 2.311.027,60
Registro Imprese Bolzano e P.IVA / Handelsregister Bozen und MwST. Nr. 00359210218
http://www.sasabz.it

________________________________
*** Rispetta l'ambiente. Non stampare questa mail se non ? necessario. ***
*** Vor dem Drucken denke bitte an die Umwelt und die Kosten. ***


Il presente messaggio ? diretto unicamente al destinatario sopra indicato.
L'utilizzo non autorizzato del presente messaggio ? vietato e potrebbe costituire reato.
Chiunque altro riceva questa comunicazione per errore ? invitato ad informarci immediatamente ed ? tenuto a distruggere quanto ricevuto.

Die obige Mitteilung ist ausschlie?lich f?r den angef?hrten Adressaten bestimmt.
Die unbefugte Verwendung dieser Mitteilung ist verboten und k?nnte strafrechtlich verfolgt werden.
Wer diese Mitteilung irrt?mlicherweise erh?lt wird gebeten uns umgehend zu informieren und anschlie?end die Mitteilung zu vernichten.

________________________________

**Pull request merged**
